#!/bin/sh

usage() {
  echo "
Usage: cvescan [options]

Options:
[no arguments - first run]	initial install/update of CVE databases and exit.

-h | --help			display this help text.
-u | --update			update CVE databases and exit.
-1 | --vulners [nmap arguments]	nmap scan using ONLY vulners NSE script.
-2 | --vulscan [nmap arguments] nmap scan using ONLY vulscan NSE script.
-3 | --all [nmap arguments]	nmap scan using BOTH vulners AND vulscan. (optional)

[nmap arguments]		Same as running with '-3' or '--all'.
				Default functionality is to use BOTH vulners AND vulscan.

The following additional arguments can be added when using '-2', '--vulscan', '-3', '--all',
(or default nmap arguments) in order to only use specific vulscan databases to return results:

--script-args vulscandb=cve.csv
--script-args vulscandb=exploitdb.csv
--script-args vulscandb=openvas.csv
--script-args vulscandb=osvdb.csv
--script-args vulscandb=scipvuldb.csv
--script-args vulscandb=securityfocus.csv
--script-args vulscandb=securitytracker.csv
--script-args vulscandb=xforce.csv
"
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage; exit 0
fi

# Make sure we're running as root:
if [ "$(id -u)" != "0" ]; then
  echo "$0 must be run as root or with 'sudo'"; exit 1
fi

# Check for dependencies:
programs="nmap git"
for program in $programs; do
  if ! command -v "$program" >/dev/null 2>&1; then
    echo "$program must already be installed to run this script"; exit 1
  fi
done

workdir="$PWD"
if uname -a | grep -qi darwin; then
  nmapdir="/usr/local/share/nmap/scripts"
else
  nmapdir="/usr/share/nmap/scripts"
fi
cd "$nmapdir" || exit 1

# Make sure vulscan is installed and updated:
if [ ! -d vulscan ]; then
  git clone https://github.com/scipag/vulscan.git
  cd vulscan/utilities/updater || exit 1
  chmod +x updateFiles.sh
  ./updateFiles.sh
  echo "Next time, run $0 with normal nmap arguments to do a CVE scan"
  exit
fi

# Options for updating vulscan databases:
if [ "$1" = "-u" ] || [ "$1" = "--update" ]; then
  cd vulscan/utilities/updater || exit 1
  ./updateFiles.sh
  exit $?
elif [ "$1" ]; then
  cd "$workdir" || exit 1
  if [ "$1" = "-1" ] || [ "$1" = "--vulners" ]; then
    shift
    if echo "${@}" | grep -q '\-sV'; then
      nmap --script vulners ${@}
    else
      nmap --script vulners -sV ${@}
    fi
  elif [ "$1" = "-2" ] || [ "$1" = "--vulscan" ]; then
    shift
    if echo "${@}" | grep -q '\-sV'; then
      nmap --script vulscan/vulscan ${@}
    else
      nmap --script vulscan/vulscan -sV ${@}
    fi
  elif [ "$1" = "-3" ] || [ "$1" = "--all" ]; then
    shift
    if echo "${@}" | grep -q '\-sV'; then
      nmap --script vulners,vulscan/vulscan ${@}
    else
      nmap --script vulners,vulscan/vulscan -sV ${@}
    fi
  else
    if echo "${@}" | grep -q '\-sV'; then
      nmap --script vulners,vulscan/vulscan ${@}
    else
      nmap --script vulners,vulscan/vulscan -sV ${@}
    fi
  fi
else
  usage; exit 1
fi


